default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: devise_bootsttap_development
  username: <%= `whoami`.chomp %>

test:
  <<: *default
  database: devise_bootstrap_test
  username: <%= `whoami`.chomp %>
